---
- name: Verificar se é VM (Segurança)
  ansible.builtin.fail:
    msg: "Abortando: Hardware Tune não deve rodar em VM."
  when: ansible_virtualization_role == "guest"

- name: Aplicar Parâmetros de Kernel (Otimizações NVMe)
  ansible.builtin.copy:
    dest: /etc/kernel/cmdline
    # Removido isolamento IOMMU/VFIO para permitir Dual Boot amigável e Secure Boot.
    # nvme_core... -> Otimização de latência para NVMe Gen4 para evitar travamentos.
    content: "root=ZFS={{ pool_name }}/ROOT/pve-1 boot=zfs nvme_core.default_ps_max_latency_us=0 split_lock_detect=off"
  notify: Refresh Bootloader

- name: Limitar RAM ZFS (Tuning ARC)
  ansible.builtin.copy:
    dest: /etc/modprobe.d/zfs.conf
    content: "options zfs zfs_arc_max={{ zfs_arc_limit_bytes }}"
  notify: Update Initramfs

# Nota: Módulos VFIO, Blacklist Nouveau/Nvidia e isolamento de GPU
# foram removidos intencionalmente para suportar Secure Boot e Dual-Boot nativo.
